# Site Settings
title: "Object-Oriented Programming"
description: "OER Object-Oriented Programming Chapters"
theme: jekyll-theme-slate

# Markdown Processor Settings
kramdown:
  input: GFM                 # Uses GitHub Flavored Markdown
  auto_ids: true             # Automatically generates header IDs for anchor links
  hard_wrap: false
